version: "3.7"

services:
  timetracker:
    image: registry.bjarke.xyz/timetracker:latest
    build:
      context: .
    networks:
      - swarm-overlay

networks:
  swarm-overlay:
    external: true
    name: swarm-overlay
